services:
  - type: web
    name: fastapi-video-api
    env: docker
    plan: free
    region: singapore  
    branch: main
    repo: https://github.com/SKKU-GDG/gdg-fastapi
    dockerfilePath: ./Dockerfile
    autoDeploy: true
